services:
  inventory-db:
    image: mysql:8.0
    container_name: inventory-mysql
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "${DB_PORT_EXTERNAL}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d # Tetap ada untuk inisialisasi awal

  inventory-flyway:
    image: flyway/flyway:latest
    container_name: inventory-flyway
    # Menghubungkan Flyway ke database dengan retries jika DB belum siap
    command: -url=jdbc:mysql://inventory-db:3306/${DB_NAME} -user=root -password=${DB_ROOT_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./init-db:/flyway/sql
    depends_on:
      - inventory-db

  inventory-api:
    build: ./Inventory_API
    container_name: inventory-api
    restart: always
    depends_on:
      - inventory-db
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:${API_PORT}
      # AllowUserVariables=True penting untuk Stored Procedure dengan Window Functions
      - ConnectionStrings__DefaultConnection=Server=inventory-db;Database=${DB_NAME};Uid=root;Pwd=${DB_ROOT_PASSWORD};AllowUserVariables=True

  inventory-web:
    build: ./inventory_app
    container_name: inventory-web
    restart: always
    depends_on:
      - inventory-api
    ports:
      - "8080:80"